server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/bewerbungsmanager
    username: nad_user
    password: nad

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
